# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160304_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='binarythreshold',
        ),
        migrations.RemoveField(
            model_name='document',
            name='edgedetection',
        ),
        migrations.RemoveField(
            model_name='document',
            name='foregroundextract',
        ),
        migrations.RemoveField(
            model_name='document',
            name='greyscale',
        ),
        migrations.RemoveField(
            model_name='document',
            name='histogram',
        ),
        migrations.RemoveField(
            model_name='document',
            name='resize',
        ),
        migrations.RemoveField(
            model_name='document',
            name='smoothen',
        ),
        migrations.RemoveField(
            model_name='document',
            name='sobelfilter',
        ),
        migrations.AddField(
            model_name='document',
            name='question',
            field=models.BooleanField(default='hello', max_length=500),
            preserve_default=False,
        ),
    ]
