# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20160311_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
